dataloader:
  batch_size: 8
  shuffle: true
optimizer:
  name: adamw
  lr: 3.0e-5
scheduler:
  name: cosine
  warmup_steps: 500
trainer:
  max_epochs: 5
  gradient_clip_norm: 1.0
  validation_samples: 3
  validation_max_length: 128
